apiVersion: v1
kind: Service
metadata:
  name: category
  namespace: ecommerce
spec:
  selector:
    app: category
  ports:
    - name: http
      port: 8094
      targetPort: 8094
    - name: grpc
      port: 9014
      targetPort: 9014
  type: ClusterIP
