apiVersion: v1
kind: Service
metadata:
  name: merchant-detail
  namespace: ecommerce
spec:
  selector:
    app: merchant-detail
  ports:
    - name: http
      port: 8087
      targetPort: 8087
    - name: grpc
      port: 9022
      targetPort: 9022
  type: ClusterIP
