apiVersion: v1
kind: Service
metadata:
  name: transaction
  namespace: ecommerce
spec:
  selector:
    app: transaction
  ports:
    - name: http
      port: 8089
      targetPort: 8089
    - name: grpc
      port: 9009
      targetPort: 9009
  type: ClusterIP
