apiVersion: v1
kind: Service
metadata:
  name: merchant-business
  namespace: ecommerce
spec:
  selector:
    app: merchant-business
  ports:
    - name: http
      port: 8086
      targetPort: 8086
    - name: grpc
      port: 9021
      targetPort: 9021
  type: ClusterIP
